[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = {path="../utils"}
tokio = { version = "1.37.0", features = ["full"] }
rand = "0.8.5"
jsonwebtoken="9.3.0"
serde = "1.0"